/* AUTO-GENERATED by packages/registry/codegen.ts — DO NOT EDIT.
 * Source of truth: packages/registry/registry.ts
 * Regenerate: pnpm -F @atlas/registry gen
 */

/** Returned instead of the capability output when the call is approval-gated. */
export interface ApprovalPending {
  approvalId: string;
  status: 'review';
}

export interface AtlasClientOptions {
  baseUrl: string;
  /** api_tokens plaintext (Bearer) or Supabase Auth JWT for the operator. */
  token?: string;
  /** Operator calls may pin a Space via the x-atlas-space header. */
  spaceId?: string;
  fetchImpl?: typeof fetch;
}

export class AtlasApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: unknown,
  ) {
    super(`Atlas API error ${status}`);
  }
}

export type MemoryAnswerInput = {
  query: string;
  budget?: number;
};
export type MemoryAnswerOutput = {
  answer?: string;
  rung?: "cache" | "playbook" | "nodes" | "model";
  confidence?: number;
  tokensSpent?: number;
};

export type MemoryIngestInput = {
  cards: Array<unknown>;
};
export type MemoryIngestOutput = {
  admitted?: number;
  skipped?: number;
};

export type MemoryDistillInput = {
  limit?: number;
};
export type MemoryDistillOutput = {
  nodes?: number;
  conflicts?: number;
};

export type MemoryAdjudicateInput = {
  nodeId: string;
  verdict: "verified" | "probable" | "quarantined";
};
export type MemoryAdjudicateOutput = Record<string, unknown>;

export type RunsExecuteInput = {
  capability: string;
  input?: Record<string, unknown>;
};
export type RunsExecuteOutput = {
  runId?: string;
  status?: string;
};

export type PlaybooksAuthorInput = {
  taskFamily: string;
  brief?: string;
};
export type PlaybooksAuthorOutput = {
  playbookId?: string;
  version?: number;
};

export type FactoryBuildSiteInput = {
  profileUrl: string;
  template?: string;
  stylePack?: string;
};
export type FactoryBuildSiteOutput = {
  siteId?: string;
  previewUrl?: string;
};

export type FactoryDeploySiteInput = {
  siteId: string;
  domain?: string;
};
export type FactoryDeploySiteOutput = {
  deployUrl?: string;
};

export type LeadsFindInput = {
  industry: string;
  location: string;
  limit?: number;
};
export type LeadsFindOutput = {
  leads?: Array<unknown>;
};

export type OutreachSendInput = {
  leadId: string;
  channel: string;
  body: string;
};
export type OutreachSendOutput = {
  approvalId?: string;
};

export type EventsSiteInput = {
  siteId: string;
  channel: string;
  payload: Record<string, unknown>;
};
export type EventsSiteOutput = {
  conversationId?: string;
};

export type ApprovalsListInput = Record<string, unknown>;
export type ApprovalsListOutput = {
  approvals?: Array<unknown>;
};

export type ApprovalsDecideInput = {
  approvalId: string;
  decision: "approved" | "rejected";
  notes?: string;
};
export type ApprovalsDecideOutput = Record<string, unknown>;

export type StatusMissionControlInput = Record<string, unknown>;
export type StatusMissionControlOutput = Record<string, unknown>;

export type BenchRunInput = {
  taskFamily?: string;
};
export type BenchRunOutput = {
  results?: Array<unknown>;
};

export class AtlasGeneratedClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly spaceId?: string;
  private readonly fetchImpl: typeof fetch;

  constructor(opts: AtlasClientOptions) {
    this.baseUrl = opts.baseUrl.endsWith('/') ? opts.baseUrl.slice(0, -1) : opts.baseUrl;
    this.token = opts.token;
    this.spaceId = opts.spaceId;
    this.fetchImpl = opts.fetchImpl ?? fetch;
  }

  private async request<T>(method: 'GET' | 'POST', path: string, input: Record<string, unknown>): Promise<T | ApprovalPending> {
    const headers: Record<string, string> = { 'content-type': 'application/json' };
    if (this.token) headers.authorization = `Bearer ${this.token}`;
    if (this.spaceId) headers['x-atlas-space'] = this.spaceId;

    let url = this.baseUrl + path;
    let body: string | undefined;
    if (method === 'GET') {
      const qs = new URLSearchParams();
      for (const [k, v] of Object.entries(input ?? {})) {
        if (v !== undefined && v !== null) qs.set(k, String(v));
      }
      const s = qs.toString();
      if (s) url += '?' + s;
    } else {
      body = JSON.stringify(input ?? {});
    }

    const res = await this.fetchImpl(url, { method, headers, body });
    const json: unknown = await res.json().catch(() => undefined);
    if (!res.ok) throw new AtlasApiError(res.status, json);
    return json as T | ApprovalPending;
  }

  /** Answer from memory — POST /v1/memory/answer */
  memoryAnswer(input: MemoryAnswerInput): Promise<MemoryAnswerOutput | ApprovalPending> {
    return this.request<MemoryAnswerOutput>("POST", "/v1/memory/answer", input);
  }

  /** Ingest cards — POST /v1/memory/ingest */
  memoryIngest(input: MemoryIngestInput): Promise<MemoryIngestOutput | ApprovalPending> {
    return this.request<MemoryIngestOutput>("POST", "/v1/memory/ingest", input);
  }

  /** Distill cards → nodes — POST /v1/memory/distill */
  memoryDistill(input: MemoryDistillInput): Promise<MemoryDistillOutput | ApprovalPending> {
    return this.request<MemoryDistillOutput>("POST", "/v1/memory/distill", input);
  }

  /** Truth review decision — POST /v1/memory/adjudicate (approval-gated: returns {approvalId, status:"review"}) */
  memoryAdjudicate(input: MemoryAdjudicateInput): Promise<MemoryAdjudicateOutput | ApprovalPending> {
    return this.request<MemoryAdjudicateOutput>("POST", "/v1/memory/adjudicate", input);
  }

  /** Execute capability run — POST /v1/runs/execute */
  runsExecute(input: RunsExecuteInput): Promise<RunsExecuteOutput | ApprovalPending> {
    return this.request<RunsExecuteOutput>("POST", "/v1/runs/execute", input);
  }

  /** Author playbook (departing genius) — POST /v1/playbooks/author (approval-gated: returns {approvalId, status:"review"}) */
  playbooksAuthor(input: PlaybooksAuthorInput): Promise<PlaybooksAuthorOutput | ApprovalPending> {
    return this.request<PlaybooksAuthorOutput>("POST", "/v1/playbooks/author", input);
  }

  /** Build wedge site — POST /v1/factory/build_site */
  factoryBuildSite(input: FactoryBuildSiteInput): Promise<FactoryBuildSiteOutput | ApprovalPending> {
    return this.request<FactoryBuildSiteOutput>("POST", "/v1/factory/build_site", input);
  }

  /** Deploy site live — POST /v1/factory/deploy_site (approval-gated: returns {approvalId, status:"review"}) */
  factoryDeploySite(input: FactoryDeploySiteInput): Promise<FactoryDeploySiteOutput | ApprovalPending> {
    return this.request<FactoryDeploySiteOutput>("POST", "/v1/factory/deploy_site", input);
  }

  /** Find leads — POST /v1/leads/find */
  leadsFind(input: LeadsFindInput): Promise<LeadsFindOutput | ApprovalPending> {
    return this.request<LeadsFindOutput>("POST", "/v1/leads/find", input);
  }

  /** Send outreach message — POST /v1/outreach/send (approval-gated: returns {approvalId, status:"review"}) */
  outreachSend(input: OutreachSendInput): Promise<OutreachSendOutput | ApprovalPending> {
    return this.request<OutreachSendOutput>("POST", "/v1/outreach/send", input);
  }

  /** Site event webhook — POST /v1/events/site */
  eventsSite(input: EventsSiteInput): Promise<EventsSiteOutput | ApprovalPending> {
    return this.request<EventsSiteOutput>("POST", "/v1/events/site", input);
  }

  /** List pending approvals — GET /v1/approvals/list */
  approvalsList(input: ApprovalsListInput): Promise<ApprovalsListOutput | ApprovalPending> {
    return this.request<ApprovalsListOutput>("GET", "/v1/approvals/list", input);
  }

  /** Decide approval — POST /v1/approvals/decide */
  approvalsDecide(input: ApprovalsDecideInput): Promise<ApprovalsDecideOutput | ApprovalPending> {
    return this.request<ApprovalsDecideOutput>("POST", "/v1/approvals/decide", input);
  }

  /** Mission Control status — GET /v1/status/mission_control */
  statusMissionControl(input: StatusMissionControlInput): Promise<StatusMissionControlOutput | ApprovalPending> {
    return this.request<StatusMissionControlOutput>("GET", "/v1/status/mission_control", input);
  }

  /** Run model bench — POST /v1/bench/run */
  benchRun(input: BenchRunInput): Promise<BenchRunOutput | ApprovalPending> {
    return this.request<BenchRunOutput>("POST", "/v1/bench/run", input);
  }
}

export function createGeneratedClient(opts: AtlasClientOptions): AtlasGeneratedClient {
  return new AtlasGeneratedClient(opts);
}
