/* AUTO-GENERATED by packages/registry/codegen.ts — DO NOT EDIT.
 * Source of truth: packages/registry/registry.ts
 * Regenerate: pnpm -F @atlas/registry gen
 */

/** Returned instead of the capability output when the call is approval-gated. */
export interface ApprovalPending {
  approvalId: string;
  status: 'review';
}

export interface AtlasClientOptions {
  baseUrl: string;
  /** api_tokens plaintext (Bearer) or Supabase Auth JWT for the operator. */
  token?: string;
  /** Operator calls may pin a Space via the x-atlas-space header. */
  spaceId?: string;
  fetchImpl?: typeof fetch;
}

export class AtlasApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: unknown,
  ) {
    super(`Atlas API error ${status}`);
  }
}

export type MemoryAnswerInput = {
  query: string;
  budget?: number;
};
export type MemoryAnswerOutput = {
  answer?: string;
  rung?: "cache" | "playbook" | "nodes" | "model";
  confidence?: number;
  tokensSpent?: number;
};

export type MemoryIngestInput = {
  cards: Array<unknown>;
};
export type MemoryIngestOutput = {
  admitted?: number;
  skipped?: number;
  quarantined?: number;
};

export type MemoryDistillInput = {
  limit?: number;
};
export type MemoryDistillOutput = {
  nodes?: number;
  conflicts?: number;
};

export type MemoryAdjudicateInput = {
  nodeId: string;
  verdict: "verified" | "probable" | "quarantined";
};
export type MemoryAdjudicateOutput = Record<string, unknown>;

export type RunsExecuteInput = {
  capability: string;
  input?: Record<string, unknown>;
};
export type RunsExecuteOutput = {
  runId?: string;
  status?: string;
};

export type PlaybooksAuthorInput = {
  taskFamily: string;
  brief?: string;
};
export type PlaybooksAuthorOutput = {
  playbookId?: string;
  version?: number;
};

export type FactoryBuildSiteInput = {
  profileUrl: string;
  region?: string;
  template?: string;
  stylePack?: string;
  facts?: Array<unknown>;
};
export type FactoryBuildSiteOutput = {
  siteId?: string;
  previewUrl?: string;
  status?: string;
  created?: boolean;
  factCount?: number;
  blocked?: Array<unknown>;
  buildHash?: string;
  renderIssues?: Array<unknown>;
  qa?: Record<string, unknown>;
};

export type FactoryPreviewInput = {
  siteId: string;
};
export type FactoryPreviewOutput = {
  html?: string;
  hash?: string;
  expiresAt?: string;
  expired?: boolean;
  issues?: Array<unknown>;
  qa?: Record<string, unknown>;
};

export type FactoryDeploySiteInput = {
  siteId: string;
  domain?: string;
};
export type FactoryDeploySiteOutput = {
  deployUrl?: string;
};

export type FactoryReviseSiteInput = {
  siteId: string;
  facts: Array<unknown>;
  template?: string;
  stylePack?: string;
  region?: string;
};
export type FactoryReviseSiteOutput = {
  siteId?: string;
  revised?: boolean;
  status?: string;
  factCount?: number;
  blocked?: Array<unknown>;
  buildHash?: string;
  renderIssues?: Array<unknown>;
  qa?: Record<string, unknown>;
  note?: string;
};

export type FactoryUnpublishInput = {
  siteId: string;
};
export type FactoryUnpublishOutput = {
  approvalId?: string;
};

export type FactoryRollbackInput = {
  siteId: string;
};
export type FactoryRollbackOutput = {
  approvalId?: string;
};

export type LeadsFindInput = {
  industry: string;
  location: string;
  limit?: number;
};
export type LeadsFindOutput = {
  leads?: Array<unknown>;
};

export type LeadsRecordInput = {
  businessName: string;
  sourceUrl: string;
  phone?: string;
  websiteUrl?: string;
  note?: string;
};
export type LeadsRecordOutput = {
  leadId?: string;
  recorded?: boolean;
  duplicateOf?: string;
  code?: string;
  note?: string;
  status?: string;
};

export type ProspectingQualifyInput = {
  leadId: string;
  evidence: Record<string, unknown>;
};
export type ProspectingQualifyOutput = {
  assessmentId?: string;
  verdict?: string;
  total?: number;
  scores?: Record<string, unknown>;
  blockers?: Array<unknown>;
  unknowns?: Array<unknown>;
  expiresAt?: string;
  status?: string;
};

export type ProspectingWorkspaceInput = {
  verdict?: string;
  limit?: number;
};
export type ProspectingWorkspaceOutput = {
  prospects?: Array<unknown>;
  queue?: Record<string, unknown>;
  status?: string;
};

export type DemosEnqueueInput = {
  leadId: string;
};
export type DemosEnqueueOutput = {
  queueId?: string;
  state?: string;
  remaining?: number;
  belowFloor?: boolean;
  expiresAt?: string;
  status?: string;
};

export type DemosAdvanceInput = {
  queueId: string;
  state: string;
  siteId?: string;
};
export type DemosAdvanceOutput = {
  queueId?: string;
  from?: string;
  to?: string;
  status?: string;
};

export type OutreachSendInput = {
  leadId: string;
  channel: string;
  body: string;
  touchId?: string;
};
export type OutreachSendOutput = {
  approvalId?: string;
};

export type AutomationSequenceInput = {
  leadId: string;
  channels: Array<unknown>;
};
export type AutomationSequenceOutput = {
  sequenceId?: string;
  version?: number;
  state?: string;
  steps?: Array<unknown>;
  planned?: boolean;
  code?: string;
  status?: string;
};

export type SequenceAdvanceInput = {
  touchId: string;
  state: string;
  approvalId?: string;
};
export type SequenceAdvanceOutput = {
  touchId?: string;
  from?: string;
  to?: string;
  sequenceState?: string;
  stopped?: boolean;
  advanced?: boolean;
  code?: string;
  status?: string;
};

export type SequenceStateInput = {
  leadId: string;
};
export type SequenceStateOutput = {
  found?: boolean;
  sequenceId?: string;
  version?: number;
  state?: string;
  stoppedReason?: string;
  touches?: Array<unknown>;
  next?: Record<string, unknown>;
  status?: string;
};

export type OffersPublishInput = {
  leadId: string;
  country: string;
  currency: string;
  priceMinor: number;
  period: string;
  termsVersion: string;
  disclosures: Record<string, unknown>;
};
export type OffersPublishOutput = {
  offerId?: string;
  version?: number;
  currency?: string;
  priceMinor?: number;
  period?: string;
  country?: string;
  supersedes?: number;
  published?: boolean;
  code?: string;
  missing?: Array<unknown>;
  required?: Array<unknown>;
  status?: string;
};

export type DealsDecideInput = {
  leadId: string;
  state: string;
  offerVersion?: number;
  notes?: string;
};
export type DealsDecideOutput = {
  decisionId?: string;
  from?: string;
  first?: boolean;
  to?: string;
  offerVersion?: number;
  decided?: boolean;
  code?: string;
  status?: string;
};

export type HostingRecordTermsInput = {
  leadId: string;
  paymentReference?: string;
};
export type HostingRecordTermsOutput = {
  entitlementId?: string;
  state?: string;
  offerVersion?: number;
  paymentRecorded?: boolean;
  recorded?: boolean;
  code?: string;
  note?: string;
  status?: string;
};

export type HostingActivateInput = {
  leadId: string;
};
export type HostingActivateOutput = {
  approvalId?: string;
};

export type HostingCancelInput = {
  leadId: string;
  servesUntil?: string;
};
export type HostingCancelOutput = {
  approvalId?: string;
};

export type HostingAdvanceInput = {
  leadId: string;
  state: string;
};
export type HostingAdvanceOutput = {
  entitlementId?: string;
  from?: string;
  state?: string;
  advanced?: boolean;
  code?: string;
  note?: string;
  status?: string;
};

export type HostingStateInput = {
  leadId: string;
};
export type HostingStateOutput = {
  offer?: Record<string, unknown>;
  deal?: Record<string, unknown>;
  entitlement?: Record<string, unknown>;
  status?: string;
};

export type PilotRecordCostInput = {
  category: string;
  leadId?: string;
  amountMinor?: number;
  currency?: string;
  minutes?: number;
  incurredOn: string;
  note: string;
};
export type PilotRecordCostOutput = {
  entryId?: string;
  category?: string;
  recorded?: boolean;
  code?: string;
  note?: string;
  status?: string;
};

export type PilotRecordOutcomeInput = {
  leadId: string;
  satisfaction: number;
  observedOn: string;
  note: string;
};
export type PilotRecordOutcomeOutput = {
  outcomeId?: string;
  satisfaction?: number;
  recorded?: boolean;
  code?: string;
  note?: string;
  status?: string;
};

export type AnalyticsFunnelInput = Record<string, unknown>;
export type AnalyticsFunnelOutput = {
  stages?: Array<unknown>;
  rates?: Record<string, unknown>;
  revenue?: Record<string, unknown>;
  unavailable?: Array<unknown>;
  empty?: boolean;
  channelContribution?: Record<string, unknown>;
  topBlockers?: Array<unknown>;
  status?: string;
  note?: string;
};

export type FactoryVerifyLiveInput = Record<string, unknown>;
export type FactoryVerifyLiveOutput = {
  checked?: number;
  matching?: number;
  healthy?: boolean;
  mismatched?: Array<unknown>;
  unreadable?: Array<unknown>;
  withdrawalsChecked?: number;
  withdrawalsConfirmed?: number;
  withdrawalsUnconfirmed?: Array<unknown>;
  status?: string;
};

export type EventsSiteInput = {
  siteId: string;
  channel: string;
  payload: Record<string, unknown>;
};
export type EventsSiteOutput = {
  conversationId?: string;
};

export type ApprovalsListInput = Record<string, unknown>;
export type ApprovalsListOutput = {
  approvals?: Array<unknown>;
};

export type ApprovalsDecideInput = {
  approvalId: string;
  decision: "approved" | "rejected";
  notes?: string;
};
export type ApprovalsDecideOutput = Record<string, unknown>;

export type StatusMissionControlInput = Record<string, unknown>;
export type StatusMissionControlOutput = Record<string, unknown>;

export type BenchRunInput = {
  taskFamily?: string;
};
export type BenchRunOutput = {
  results?: Array<unknown>;
};

export class AtlasGeneratedClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly spaceId?: string;
  private readonly fetchImpl: typeof fetch;

  constructor(opts: AtlasClientOptions) {
    this.baseUrl = opts.baseUrl.endsWith('/') ? opts.baseUrl.slice(0, -1) : opts.baseUrl;
    this.token = opts.token;
    this.spaceId = opts.spaceId;
    // Bind to globalThis: browsers reject window.fetch invoked with any other
    // receiver, and this is stored then called as this.fetchImpl(...).
    this.fetchImpl = opts.fetchImpl ?? fetch.bind(globalThis);
  }

  private async request<T>(method: 'GET' | 'POST', path: string, input: Record<string, unknown>): Promise<T | ApprovalPending> {
    const headers: Record<string, string> = { 'content-type': 'application/json' };
    if (this.token) headers.authorization = `Bearer ${this.token}`;
    if (this.spaceId) headers['x-atlas-space'] = this.spaceId;

    let url = this.baseUrl + path;
    let body: string | undefined;
    if (method === 'GET') {
      const qs = new URLSearchParams();
      for (const [k, v] of Object.entries(input ?? {})) {
        if (v !== undefined && v !== null) qs.set(k, String(v));
      }
      const s = qs.toString();
      if (s) url += '?' + s;
    } else {
      body = JSON.stringify(input ?? {});
    }

    const res = await this.fetchImpl(url, { method, headers, body });
    const json: unknown = await res.json().catch(() => undefined);
    if (!res.ok) throw new AtlasApiError(res.status, json);
    return json as T | ApprovalPending;
  }

  /** Answer from memory — POST /v1/memory/answer */
  memoryAnswer(input: MemoryAnswerInput): Promise<MemoryAnswerOutput | ApprovalPending> {
    return this.request<MemoryAnswerOutput>("POST", "/v1/memory/answer", input);
  }

  /** Ingest cards — POST /v1/memory/ingest */
  memoryIngest(input: MemoryIngestInput): Promise<MemoryIngestOutput | ApprovalPending> {
    return this.request<MemoryIngestOutput>("POST", "/v1/memory/ingest", input);
  }

  /** Distill cards → nodes — POST /v1/memory/distill */
  memoryDistill(input: MemoryDistillInput): Promise<MemoryDistillOutput | ApprovalPending> {
    return this.request<MemoryDistillOutput>("POST", "/v1/memory/distill", input);
  }

  /** Truth review decision — POST /v1/memory/adjudicate (approval-gated: returns {approvalId, status:"review"}) */
  memoryAdjudicate(input: MemoryAdjudicateInput): Promise<MemoryAdjudicateOutput | ApprovalPending> {
    return this.request<MemoryAdjudicateOutput>("POST", "/v1/memory/adjudicate", input);
  }

  /** Execute capability run — POST /v1/runs/execute */
  runsExecute(input: RunsExecuteInput): Promise<RunsExecuteOutput | ApprovalPending> {
    return this.request<RunsExecuteOutput>("POST", "/v1/runs/execute", input);
  }

  /** Author playbook (departing genius) — POST /v1/playbooks/author (approval-gated: returns {approvalId, status:"review"}) */
  playbooksAuthor(input: PlaybooksAuthorInput): Promise<PlaybooksAuthorOutput | ApprovalPending> {
    return this.request<PlaybooksAuthorOutput>("POST", "/v1/playbooks/author", input);
  }

  /** Build wedge site — POST /v1/factory/build_site */
  factoryBuildSite(input: FactoryBuildSiteInput): Promise<FactoryBuildSiteOutput | ApprovalPending> {
    return this.request<FactoryBuildSiteOutput>("POST", "/v1/factory/build_site", input);
  }

  /** Preview built site — GET /v1/factory/preview */
  factoryPreview(input: FactoryPreviewInput): Promise<FactoryPreviewOutput | ApprovalPending> {
    return this.request<FactoryPreviewOutput>("GET", "/v1/factory/preview", input);
  }

  /** Deploy site live — POST /v1/factory/deploy_site (approval-gated: returns {approvalId, status:"review"}) */
  factoryDeploySite(input: FactoryDeploySiteInput): Promise<FactoryDeploySiteOutput | ApprovalPending> {
    return this.request<FactoryDeploySiteOutput>("POST", "/v1/factory/deploy_site", input);
  }

  /** Revise a site — POST /v1/factory/revise_site */
  factoryReviseSite(input: FactoryReviseSiteInput): Promise<FactoryReviseSiteOutput | ApprovalPending> {
    return this.request<FactoryReviseSiteOutput>("POST", "/v1/factory/revise_site", input);
  }

  /** Withdraw a live site — POST /v1/factory/unpublish (approval-gated: returns {approvalId, status:"review"}) */
  factoryUnpublish(input: FactoryUnpublishInput): Promise<FactoryUnpublishOutput | ApprovalPending> {
    return this.request<FactoryUnpublishOutput>("POST", "/v1/factory/unpublish", input);
  }

  /** Roll a site back — POST /v1/factory/rollback (approval-gated: returns {approvalId, status:"review"}) */
  factoryRollback(input: FactoryRollbackInput): Promise<FactoryRollbackOutput | ApprovalPending> {
    return this.request<FactoryRollbackOutput>("POST", "/v1/factory/rollback", input);
  }

  /** Find leads — POST /v1/leads/find */
  leadsFind(input: LeadsFindInput): Promise<LeadsFindOutput | ApprovalPending> {
    return this.request<LeadsFindOutput>("POST", "/v1/leads/find", input);
  }

  /** Record a sourced lead — POST /v1/leads/record */
  leadsRecord(input: LeadsRecordInput): Promise<LeadsRecordOutput | ApprovalPending> {
    return this.request<LeadsRecordOutput>("POST", "/v1/leads/record", input);
  }

  /** Qualify prospect — POST /v1/prospecting/qualify */
  prospectingQualify(input: ProspectingQualifyInput): Promise<ProspectingQualifyOutput | ApprovalPending> {
    return this.request<ProspectingQualifyOutput>("POST", "/v1/prospecting/qualify", input);
  }

  /** Prospecting workspace — GET /v1/prospecting/workspace */
  prospectingWorkspace(input: ProspectingWorkspaceInput): Promise<ProspectingWorkspaceOutput | ApprovalPending> {
    return this.request<ProspectingWorkspaceOutput>("GET", "/v1/prospecting/workspace", input);
  }

  /** Take a demo slot — POST /v1/demos/enqueue */
  demosEnqueue(input: DemosEnqueueInput): Promise<DemosEnqueueOutput | ApprovalPending> {
    return this.request<DemosEnqueueOutput>("POST", "/v1/demos/enqueue", input);
  }

  /** Move a demo along — POST /v1/demos/advance */
  demosAdvance(input: DemosAdvanceInput): Promise<DemosAdvanceOutput | ApprovalPending> {
    return this.request<DemosAdvanceOutput>("POST", "/v1/demos/advance", input);
  }

  /** Send outreach message — POST /v1/outreach/send (approval-gated: returns {approvalId, status:"review"}) */
  outreachSend(input: OutreachSendInput): Promise<OutreachSendOutput | ApprovalPending> {
    return this.request<OutreachSendOutput>("POST", "/v1/outreach/send", input);
  }

  /** Plan an outreach sequence — POST /v1/automation/sequence */
  automationSequence(input: AutomationSequenceInput): Promise<AutomationSequenceOutput | ApprovalPending> {
    return this.request<AutomationSequenceOutput>("POST", "/v1/automation/sequence", input);
  }

  /** Record a touch outcome — POST /v1/sequence/advance */
  sequenceAdvance(input: SequenceAdvanceInput): Promise<SequenceAdvanceOutput | ApprovalPending> {
    return this.request<SequenceAdvanceOutput>("POST", "/v1/sequence/advance", input);
  }

  /** Outreach sequence state — GET /v1/sequence/state */
  sequenceState(input: SequenceStateInput): Promise<SequenceStateOutput | ApprovalPending> {
    return this.request<SequenceStateOutput>("GET", "/v1/sequence/state", input);
  }

  /** Publish an offer version — POST /v1/offers/publish */
  offersPublish(input: OffersPublishInput): Promise<OffersPublishOutput | ApprovalPending> {
    return this.request<OffersPublishOutput>("POST", "/v1/offers/publish", input);
  }

  /** Record a deal decision — POST /v1/deals/decide */
  dealsDecide(input: DealsDecideInput): Promise<DealsDecideOutput | ApprovalPending> {
    return this.request<DealsDecideOutput>("POST", "/v1/deals/decide", input);
  }

  /** Record accepted terms — POST /v1/hosting/record_terms */
  hostingRecordTerms(input: HostingRecordTermsInput): Promise<HostingRecordTermsOutput | ApprovalPending> {
    return this.request<HostingRecordTermsOutput>("POST", "/v1/hosting/record_terms", input);
  }

  /** Activate hosting — POST /v1/hosting/activate (approval-gated: returns {approvalId, status:"review"}) */
  hostingActivate(input: HostingActivateInput): Promise<HostingActivateOutput | ApprovalPending> {
    return this.request<HostingActivateOutput>("POST", "/v1/hosting/activate", input);
  }

  /** Cancel hosting — POST /v1/hosting/cancel (approval-gated: returns {approvalId, status:"review"}) */
  hostingCancel(input: HostingCancelInput): Promise<HostingCancelOutput | ApprovalPending> {
    return this.request<HostingCancelOutput>("POST", "/v1/hosting/cancel", input);
  }

  /** Advance hosting delivery — POST /v1/hosting/advance */
  hostingAdvance(input: HostingAdvanceInput): Promise<HostingAdvanceOutput | ApprovalPending> {
    return this.request<HostingAdvanceOutput>("POST", "/v1/hosting/advance", input);
  }

  /** Hosting state — GET /v1/hosting/state */
  hostingState(input: HostingStateInput): Promise<HostingStateOutput | ApprovalPending> {
    return this.request<HostingStateOutput>("GET", "/v1/hosting/state", input);
  }

  /** Record a pilot cost — POST /v1/pilot/record_cost */
  pilotRecordCost(input: PilotRecordCostInput): Promise<PilotRecordCostOutput | ApprovalPending> {
    return this.request<PilotRecordCostOutput>("POST", "/v1/pilot/record_cost", input);
  }

  /** Record a pilot outcome — POST /v1/pilot/record_outcome */
  pilotRecordOutcome(input: PilotRecordOutcomeInput): Promise<PilotRecordOutcomeOutput | ApprovalPending> {
    return this.request<PilotRecordOutcomeOutput>("POST", "/v1/pilot/record_outcome", input);
  }

  /** Revenue pilot funnel — GET /v1/analytics/funnel */
  analyticsFunnel(input: AnalyticsFunnelInput): Promise<AnalyticsFunnelOutput | ApprovalPending> {
    return this.request<AnalyticsFunnelOutput>("GET", "/v1/analytics/funnel", input);
  }

  /** Verify live sites — POST /v1/factory/verify_live */
  factoryVerifyLive(input: FactoryVerifyLiveInput): Promise<FactoryVerifyLiveOutput | ApprovalPending> {
    return this.request<FactoryVerifyLiveOutput>("POST", "/v1/factory/verify_live", input);
  }

  /** Site event webhook — POST /v1/events/site */
  eventsSite(input: EventsSiteInput): Promise<EventsSiteOutput | ApprovalPending> {
    return this.request<EventsSiteOutput>("POST", "/v1/events/site", input);
  }

  /** List pending approvals — GET /v1/approvals/list */
  approvalsList(input: ApprovalsListInput): Promise<ApprovalsListOutput | ApprovalPending> {
    return this.request<ApprovalsListOutput>("GET", "/v1/approvals/list", input);
  }

  /** Decide approval — POST /v1/approvals/decide */
  approvalsDecide(input: ApprovalsDecideInput): Promise<ApprovalsDecideOutput | ApprovalPending> {
    return this.request<ApprovalsDecideOutput>("POST", "/v1/approvals/decide", input);
  }

  /** Mission Control status — GET /v1/status/mission_control */
  statusMissionControl(input: StatusMissionControlInput): Promise<StatusMissionControlOutput | ApprovalPending> {
    return this.request<StatusMissionControlOutput>("GET", "/v1/status/mission_control", input);
  }

  /** Run model bench — POST /v1/bench/run */
  benchRun(input: BenchRunInput): Promise<BenchRunOutput | ApprovalPending> {
    return this.request<BenchRunOutput>("POST", "/v1/bench/run", input);
  }
}

export function createGeneratedClient(opts: AtlasClientOptions): AtlasGeneratedClient {
  return new AtlasGeneratedClient(opts);
}
