/* AUTO-GENERATED by packages/registry/codegen.ts — DO NOT EDIT.
 * Source of truth: packages/registry/registry.ts
 * Regenerate: pnpm -F @atlas/registry gen
 */

import type { FastifyInstance } from 'fastify';
import { registerCapabilityRoute, type CapabilityRouteMeta, type PipelineDeps } from './pipeline.js';

export const GENERATED_CAPABILITY_IDS = [
  "memory.answer",
  "memory.ingest",
  "memory.distill",
  "memory.adjudicate",
  "runs.execute",
  "playbooks.author",
  "factory.build_site",
  "factory.preview",
  "factory.deploy_site",
  "factory.revise_site",
  "factory.unpublish",
  "factory.rollback",
  "leads.find",
  "prospecting.qualify",
  "prospecting.workspace",
  "demos.enqueue",
  "demos.advance",
  "outreach.send",
  "automation.sequence",
  "sequence.advance",
  "sequence.state",
  "offers.publish",
  "deals.decide",
  "hosting.activate",
  "hosting.cancel",
  "hosting.state",
  "analytics.funnel",
  "factory.verify_live",
  "events.site",
  "approvals.list",
  "approvals.decide",
  "status.mission_control",
  "bench.run"
] as const;

export function registerGeneratedRoutes(app: FastifyInstance, deps: PipelineDeps): void {
  registerCapabilityRoute(app, {
    "id": "memory.answer",
    "name": "Answer from memory",
    "path": "/v1/memory/answer",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "memory:read"
    ],
    "input": {
      "type": "object",
      "required": [
        "query"
      ],
      "properties": {
        "query": {
          "type": "string"
        },
        "budget": {
          "type": "number"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "answer": {
          "type": "string"
        },
        "rung": {
          "enum": [
            "cache",
            "playbook",
            "nodes",
            "model"
          ]
        },
        "confidence": {
          "type": "number"
        },
        "tokensSpent": {
          "type": "number"
        }
      }
    },
    "execution": "model"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "memory.ingest",
    "name": "Ingest cards",
    "path": "/v1/memory/ingest",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "memory:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "cards"
      ],
      "properties": {
        "cards": {
          "type": "array"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "admitted": {
          "type": "number"
        },
        "skipped": {
          "type": "number"
        },
        "quarantined": {
          "type": "number"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "memory.distill",
    "name": "Distill cards → nodes",
    "path": "/v1/memory/distill",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object",
      "properties": {
        "limit": {
          "type": "number"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "nodes": {
          "type": "number"
        },
        "conflicts": {
          "type": "number"
        }
      }
    },
    "execution": "model"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "memory.adjudicate",
    "name": "Truth review decision",
    "path": "/v1/memory/adjudicate",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "nodeId",
        "verdict"
      ],
      "properties": {
        "nodeId": {
          "type": "string"
        },
        "verdict": {
          "enum": [
            "verified",
            "probable",
            "quarantined"
          ]
        }
      }
    },
    "output": {
      "type": "object"
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "runs.execute",
    "name": "Execute capability run",
    "path": "/v1/runs/execute",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "runs:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "capability"
      ],
      "properties": {
        "capability": {
          "type": "string"
        },
        "input": {
          "type": "object"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "runId": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "playbooks.author",
    "name": "Author playbook (departing genius)",
    "path": "/v1/playbooks/author",
    "method": "POST",
    "taskClass": "think",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "taskFamily"
      ],
      "properties": {
        "taskFamily": {
          "type": "string"
        },
        "brief": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "playbookId": {
          "type": "string"
        },
        "version": {
          "type": "number"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.build_site",
    "name": "Build wedge site",
    "path": "/v1/factory/build_site",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "factory:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "profileUrl"
      ],
      "properties": {
        "profileUrl": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "template": {
          "type": "string"
        },
        "stylePack": {
          "type": "string"
        },
        "facts": {
          "type": "array"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "siteId": {
          "type": "string"
        },
        "previewUrl": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "created": {
          "type": "boolean"
        },
        "factCount": {
          "type": "number"
        },
        "blocked": {
          "type": "array"
        },
        "buildHash": {
          "type": "string"
        },
        "renderIssues": {
          "type": "array"
        },
        "qa": {
          "type": "object"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.preview",
    "name": "Preview built site",
    "path": "/v1/factory/preview",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "factory:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "siteId"
      ],
      "properties": {
        "siteId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "html": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        },
        "expiresAt": {
          "type": "string"
        },
        "expired": {
          "type": "boolean"
        },
        "issues": {
          "type": "array"
        },
        "qa": {
          "type": "object"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.deploy_site",
    "name": "Deploy site live",
    "path": "/v1/factory/deploy_site",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "siteId"
      ],
      "properties": {
        "siteId": {
          "type": "string"
        },
        "domain": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "deployUrl": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.revise_site",
    "name": "Revise a site",
    "path": "/v1/factory/revise_site",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "factory:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "siteId",
        "facts"
      ],
      "properties": {
        "siteId": {
          "type": "string"
        },
        "facts": {
          "type": "array"
        },
        "template": {
          "type": "string"
        },
        "stylePack": {
          "type": "string"
        },
        "region": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "siteId": {
          "type": "string"
        },
        "revised": {
          "type": "boolean"
        },
        "status": {
          "type": "string"
        },
        "factCount": {
          "type": "number"
        },
        "blocked": {
          "type": "array"
        },
        "buildHash": {
          "type": "string"
        },
        "renderIssues": {
          "type": "array"
        },
        "qa": {
          "type": "object"
        },
        "note": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.unpublish",
    "name": "Withdraw a live site",
    "path": "/v1/factory/unpublish",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "siteId"
      ],
      "properties": {
        "siteId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "approvalId": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.rollback",
    "name": "Roll a site back",
    "path": "/v1/factory/rollback",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "siteId"
      ],
      "properties": {
        "siteId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "approvalId": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "leads.find",
    "name": "Find leads",
    "path": "/v1/leads/find",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "industry",
        "location"
      ],
      "properties": {
        "industry": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "limit": {
          "type": "number"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "leads": {
          "type": "array"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "prospecting.qualify",
    "name": "Qualify prospect",
    "path": "/v1/prospecting/qualify",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "leadId",
        "evidence"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        },
        "evidence": {
          "type": "object"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "assessmentId": {
          "type": "string"
        },
        "verdict": {
          "type": "string"
        },
        "total": {
          "type": "number"
        },
        "scores": {
          "type": "object"
        },
        "blockers": {
          "type": "array"
        },
        "unknowns": {
          "type": "array"
        },
        "expiresAt": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "prospecting.workspace",
    "name": "Prospecting workspace",
    "path": "/v1/prospecting/workspace",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "properties": {
        "verdict": {
          "type": "string"
        },
        "limit": {
          "type": "number"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "prospects": {
          "type": "array"
        },
        "queue": {
          "type": "object"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "demos.enqueue",
    "name": "Take a demo slot",
    "path": "/v1/demos/enqueue",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "leadId"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "queueId": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "remaining": {
          "type": "number"
        },
        "belowFloor": {
          "type": "boolean"
        },
        "expiresAt": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "demos.advance",
    "name": "Move a demo along",
    "path": "/v1/demos/advance",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "queueId",
        "state"
      ],
      "properties": {
        "queueId": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "siteId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "queueId": {
          "type": "string"
        },
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "outreach.send",
    "name": "Send outreach message",
    "path": "/v1/outreach/send",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "leadId",
        "channel",
        "body"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "touchId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "approvalId": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "automation.sequence",
    "name": "Plan an outreach sequence",
    "path": "/v1/automation/sequence",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "leadId",
        "channels"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        },
        "channels": {
          "type": "array"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "sequenceId": {
          "type": "string"
        },
        "version": {
          "type": "number"
        },
        "state": {
          "type": "string"
        },
        "steps": {
          "type": "array"
        },
        "planned": {
          "type": "boolean"
        },
        "code": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "sequence.advance",
    "name": "Record a touch outcome",
    "path": "/v1/sequence/advance",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "touchId",
        "state"
      ],
      "properties": {
        "touchId": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "approvalId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "touchId": {
          "type": "string"
        },
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "sequenceState": {
          "type": "string"
        },
        "stopped": {
          "type": "boolean"
        },
        "advanced": {
          "type": "boolean"
        },
        "code": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "sequence.state",
    "name": "Outreach sequence state",
    "path": "/v1/sequence/state",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "leadId"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "found": {
          "type": "boolean"
        },
        "sequenceId": {
          "type": "string"
        },
        "version": {
          "type": "number"
        },
        "state": {
          "type": "string"
        },
        "stoppedReason": {
          "type": "string"
        },
        "touches": {
          "type": "array"
        },
        "next": {
          "type": "object"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "offers.publish",
    "name": "Publish an offer version",
    "path": "/v1/offers/publish",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "leadId",
        "country",
        "currency",
        "priceMinor",
        "period",
        "termsVersion",
        "disclosures"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "currency": {
          "type": "string"
        },
        "priceMinor": {
          "type": "number"
        },
        "period": {
          "type": "string"
        },
        "termsVersion": {
          "type": "string"
        },
        "disclosures": {
          "type": "object"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "offerId": {
          "type": "string"
        },
        "version": {
          "type": "number"
        },
        "currency": {
          "type": "string"
        },
        "priceMinor": {
          "type": "number"
        },
        "period": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "supersedes": {
          "type": "number"
        },
        "published": {
          "type": "boolean"
        },
        "code": {
          "type": "string"
        },
        "missing": {
          "type": "array"
        },
        "required": {
          "type": "array"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "deals.decide",
    "name": "Record a deal decision",
    "path": "/v1/deals/decide",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "leadId",
        "state"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "offerVersion": {
          "type": "number"
        },
        "notes": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "decisionId": {
          "type": "string"
        },
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "offerVersion": {
          "type": "number"
        },
        "decided": {
          "type": "boolean"
        },
        "code": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "hosting.activate",
    "name": "Activate hosting",
    "path": "/v1/hosting/activate",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "leadId"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "approvalId": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "hosting.cancel",
    "name": "Cancel hosting",
    "path": "/v1/hosting/cancel",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "leadId"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        },
        "servesUntil": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "approvalId": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "hosting.state",
    "name": "Hosting state",
    "path": "/v1/hosting/state",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "leadId"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "offer": {
          "type": "object"
        },
        "deal": {
          "type": "object"
        },
        "entitlement": {
          "type": "object"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "analytics.funnel",
    "name": "Revenue pilot funnel",
    "path": "/v1/analytics/funnel",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "properties": {}
    },
    "output": {
      "type": "object",
      "properties": {
        "stages": {
          "type": "array"
        },
        "rates": {
          "type": "object"
        },
        "revenue": {
          "type": "object"
        },
        "unavailable": {
          "type": "array"
        },
        "empty": {
          "type": "boolean"
        },
        "channelContribution": {
          "type": "object"
        },
        "topBlockers": {
          "type": "array"
        },
        "status": {
          "type": "string"
        },
        "note": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.verify_live",
    "name": "Verify live sites",
    "path": "/v1/factory/verify_live",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "factory:write"
    ],
    "input": {
      "type": "object",
      "properties": {}
    },
    "output": {
      "type": "object",
      "properties": {
        "checked": {
          "type": "number"
        },
        "matching": {
          "type": "number"
        },
        "healthy": {
          "type": "boolean"
        },
        "mismatched": {
          "type": "array"
        },
        "unreadable": {
          "type": "array"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "events.site",
    "name": "Site event webhook",
    "path": "/v1/events/site",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "events:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "siteId",
        "channel",
        "payload"
      ],
      "properties": {
        "siteId": {
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "payload": {
          "type": "object"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "conversationId": {
          "type": "string"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "approvals.list",
    "name": "List pending approvals",
    "path": "/v1/approvals/list",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object"
    },
    "output": {
      "type": "object",
      "properties": {
        "approvals": {
          "type": "array"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "approvals.decide",
    "name": "Decide approval",
    "path": "/v1/approvals/decide",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "approvalId",
        "decision"
      ],
      "properties": {
        "approvalId": {
          "type": "string"
        },
        "decision": {
          "enum": [
            "approved",
            "rejected"
          ]
        },
        "notes": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object"
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "status.mission_control",
    "name": "Mission Control status",
    "path": "/v1/status/mission_control",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object"
    },
    "output": {
      "type": "object"
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "bench.run",
    "name": "Run model bench",
    "path": "/v1/bench/run",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object",
      "properties": {
        "taskFamily": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array"
        }
      }
    },
    "execution": "handler"
  } as const satisfies CapabilityRouteMeta, deps);
}
