/* AUTO-GENERATED by packages/registry/codegen.ts — DO NOT EDIT.
 * Source of truth: packages/registry/registry.ts
 * Regenerate: pnpm -F @atlas/registry gen
 */

import type { FastifyInstance } from 'fastify';
import { registerCapabilityRoute, type CapabilityRouteMeta, type PipelineDeps } from './pipeline.js';

export const GENERATED_CAPABILITY_IDS = [
  "memory.answer",
  "memory.ingest",
  "memory.distill",
  "memory.adjudicate",
  "runs.execute",
  "playbooks.author",
  "factory.build_site",
  "factory.deploy_site",
  "leads.find",
  "outreach.send",
  "events.site",
  "approvals.list",
  "approvals.decide",
  "status.mission_control",
  "bench.run"
] as const;

export function registerGeneratedRoutes(app: FastifyInstance, deps: PipelineDeps): void {
  registerCapabilityRoute(app, {
    "id": "memory.answer",
    "name": "Answer from memory",
    "path": "/v1/memory/answer",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "memory:read"
    ],
    "input": {
      "type": "object",
      "required": [
        "query"
      ],
      "properties": {
        "query": {
          "type": "string"
        },
        "budget": {
          "type": "number"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "answer": {
          "type": "string"
        },
        "rung": {
          "enum": [
            "cache",
            "playbook",
            "nodes",
            "model"
          ]
        },
        "confidence": {
          "type": "number"
        },
        "tokensSpent": {
          "type": "number"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "memory.ingest",
    "name": "Ingest cards",
    "path": "/v1/memory/ingest",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "memory:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "cards"
      ],
      "properties": {
        "cards": {
          "type": "array"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "admitted": {
          "type": "number"
        },
        "skipped": {
          "type": "number"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "memory.distill",
    "name": "Distill cards → nodes",
    "path": "/v1/memory/distill",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object",
      "properties": {
        "limit": {
          "type": "number"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "nodes": {
          "type": "number"
        },
        "conflicts": {
          "type": "number"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "memory.adjudicate",
    "name": "Truth review decision",
    "path": "/v1/memory/adjudicate",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "nodeId",
        "verdict"
      ],
      "properties": {
        "nodeId": {
          "type": "string"
        },
        "verdict": {
          "enum": [
            "verified",
            "probable",
            "quarantined"
          ]
        }
      }
    },
    "output": {
      "type": "object"
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "runs.execute",
    "name": "Execute capability run",
    "path": "/v1/runs/execute",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "runs:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "capability"
      ],
      "properties": {
        "capability": {
          "type": "string"
        },
        "input": {
          "type": "object"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "runId": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "playbooks.author",
    "name": "Author playbook (departing genius)",
    "path": "/v1/playbooks/author",
    "method": "POST",
    "taskClass": "think",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "taskFamily"
      ],
      "properties": {
        "taskFamily": {
          "type": "string"
        },
        "brief": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "playbookId": {
          "type": "string"
        },
        "version": {
          "type": "number"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.build_site",
    "name": "Build wedge site",
    "path": "/v1/factory/build_site",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "factory:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "profileUrl"
      ],
      "properties": {
        "profileUrl": {
          "type": "string"
        },
        "template": {
          "type": "string"
        },
        "stylePack": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "siteId": {
          "type": "string"
        },
        "previewUrl": {
          "type": "string"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "factory.deploy_site",
    "name": "Deploy site live",
    "path": "/v1/factory/deploy_site",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "siteId"
      ],
      "properties": {
        "siteId": {
          "type": "string"
        },
        "domain": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "deployUrl": {
          "type": "string"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "leads.find",
    "name": "Find leads",
    "path": "/v1/leads/find",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [
      "leads:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "industry",
        "location"
      ],
      "properties": {
        "industry": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "limit": {
          "type": "number"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "leads": {
          "type": "array"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "outreach.send",
    "name": "Send outreach message",
    "path": "/v1/outreach/send",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": true,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "leadId",
        "channel",
        "body"
      ],
      "properties": {
        "leadId": {
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "body": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "approvalId": {
          "type": "string"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "events.site",
    "name": "Site event webhook",
    "path": "/v1/events/site",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [
      "events:write"
    ],
    "input": {
      "type": "object",
      "required": [
        "siteId",
        "channel",
        "payload"
      ],
      "properties": {
        "siteId": {
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "payload": {
          "type": "object"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "conversationId": {
          "type": "string"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "approvals.list",
    "name": "List pending approvals",
    "path": "/v1/approvals/list",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object"
    },
    "output": {
      "type": "object",
      "properties": {
        "approvals": {
          "type": "array"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "approvals.decide",
    "name": "Decide approval",
    "path": "/v1/approvals/decide",
    "method": "POST",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object",
      "required": [
        "approvalId",
        "decision"
      ],
      "properties": {
        "approvalId": {
          "type": "string"
        },
        "decision": {
          "enum": [
            "approved",
            "rejected"
          ]
        },
        "notes": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object"
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "status.mission_control",
    "name": "Mission Control status",
    "path": "/v1/status/mission_control",
    "method": "GET",
    "taskClass": "quick",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object"
    },
    "output": {
      "type": "object"
    }
  } as const satisfies CapabilityRouteMeta, deps);
  registerCapabilityRoute(app, {
    "id": "bench.run",
    "name": "Run model bench",
    "path": "/v1/bench/run",
    "method": "POST",
    "taskClass": "do",
    "requiresApproval": false,
    "scopes": [],
    "input": {
      "type": "object",
      "properties": {
        "taskFamily": {
          "type": "string"
        }
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array"
        }
      }
    }
  } as const satisfies CapabilityRouteMeta, deps);
}
