/**
 * ATLAS OS — Registry codegen (P1, Codex lane).
 * Reads registry.ts (single source of truth) and emits:
 *   - apps/api/src/routes.gen.ts      — one Fastify route per capability
 *   - packages/client/src/client.gen.ts — typed client method per capability
 * Route path contract: '/v1/' + id.replace('.', '/')  (see registry.ts footer).
 * Run via:  pnpm -F @atlas/registry gen   (or the api build step).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { registry, type Capability } from './registry.js';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');

const HEADER = `/* AUTO-GENERATED by packages/registry/codegen.ts — DO NOT EDIT.
 * Source of truth: packages/registry/registry.ts
 * Regenerate: pnpm -F @atlas/registry gen
 */
`;

// ---------- helpers ----------

function routePath(id: string): string {
  return '/v1/' + id.split('.').join('/');
}

function methodName(id: string): string {
  // memory.answer -> memoryAnswer ; status.mission_control -> statusMissionControl
  return id
    .split(/[._]/)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

function typeName(id: string): string {
  const m = methodName(id);
  return m.charAt(0).toUpperCase() + m.slice(1);
}

interface JsonSchema {
  type?: string;
  enum?: unknown[];
  required?: string[];
  properties?: Record<string, JsonSchema>;
  items?: JsonSchema;
}

/** Minimal JSON-schema → TS type text. Unknown shapes degrade to `unknown`. */
function tsType(schema: JsonSchema | undefined, indent = '  '): string {
  if (!schema) return 'unknown';
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(' | ');
  switch (schema.type) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return `Array<${tsType(schema.items, indent)}>`;
    case 'object': {
      const props = schema.properties;
      if (!props || Object.keys(props).length === 0) return 'Record<string, unknown>';
      const required = new Set(schema.required ?? []);
      const lines = Object.entries(props).map(([key, prop]) => {
        const opt = required.has(key) ? '' : '?';
        return `${indent}${key}${opt}: ${tsType(prop, indent + '  ')};`;
      });
      return `{\n${lines.join('\n')}\n${indent.slice(2)}}`;
    }
    default:
      return 'unknown';
  }
}

// ---------- routes.gen.ts ----------

function genRoutes(caps: Capability[]): string {
  const entries = caps
    .map((cap) => {
      const meta = {
        id: cap.id,
        name: cap.name,
        path: routePath(cap.id),
        method: cap.method,
        taskClass: cap.taskClass,
        requiresApproval: cap.requiresApproval,
        scopes: cap.scopes,
        input: cap.input,
        output: cap.output,
      };
      return `  registerCapabilityRoute(app, ${JSON.stringify(meta, null, 2).split('\n').join('\n  ')} as const satisfies CapabilityRouteMeta, deps);`;
    })
    .join('\n');

  return `${HEADER}
import type { FastifyInstance } from 'fastify';
import { registerCapabilityRoute, type CapabilityRouteMeta, type PipelineDeps } from './pipeline.js';

export const GENERATED_CAPABILITY_IDS = ${JSON.stringify(caps.map((c) => c.id), null, 2)} as const;

export function registerGeneratedRoutes(app: FastifyInstance, deps: PipelineDeps): void {
${entries}
}
`;
}

// ---------- client.gen.ts ----------

function genClient(caps: Capability[]): string {
  const typeDefs = caps
    .map((cap) => {
      const t = typeName(cap.id);
      return `export type ${t}Input = ${tsType(cap.input as JsonSchema)};\nexport type ${t}Output = ${tsType(cap.output as JsonSchema)};`;
    })
    .join('\n\n');

  const methods = caps
    .map((cap) => {
      const m = methodName(cap.id);
      const t = typeName(cap.id);
      return `  /** ${cap.name} — ${cap.method} ${routePath(cap.id)}${cap.requiresApproval ? ' (approval-gated: returns {approvalId, status:"review"})' : ''} */
  ${m}(input: ${t}Input): Promise<${t}Output | ApprovalPending> {
    return this.request<${t}Output>(${JSON.stringify(cap.method)}, ${JSON.stringify(routePath(cap.id))}, input);
  }`;
    })
    .join('\n\n');

  return `${HEADER}
/** Returned instead of the capability output when the call is approval-gated. */
export interface ApprovalPending {
  approvalId: string;
  status: 'review';
}

export interface AtlasClientOptions {
  baseUrl: string;
  /** api_tokens plaintext (Bearer) or Supabase Auth JWT for the operator. */
  token?: string;
  /** Operator calls may pin a Space via the x-atlas-space header. */
  spaceId?: string;
  fetchImpl?: typeof fetch;
}

export class AtlasApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: unknown,
  ) {
    super(\`Atlas API error \${status}\`);
  }
}

${typeDefs}

export class AtlasGeneratedClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly spaceId?: string;
  private readonly fetchImpl: typeof fetch;

  constructor(opts: AtlasClientOptions) {
    this.baseUrl = opts.baseUrl.endsWith('/') ? opts.baseUrl.slice(0, -1) : opts.baseUrl;
    this.token = opts.token;
    this.spaceId = opts.spaceId;
    this.fetchImpl = opts.fetchImpl ?? fetch;
  }

  private async request<T>(method: 'GET' | 'POST', path: string, input: Record<string, unknown>): Promise<T | ApprovalPending> {
    const headers: Record<string, string> = { 'content-type': 'application/json' };
    if (this.token) headers.authorization = \`Bearer \${this.token}\`;
    if (this.spaceId) headers['x-atlas-space'] = this.spaceId;

    let url = this.baseUrl + path;
    let body: string | undefined;
    if (method === 'GET') {
      const qs = new URLSearchParams();
      for (const [k, v] of Object.entries(input ?? {})) {
        if (v !== undefined && v !== null) qs.set(k, String(v));
      }
      const s = qs.toString();
      if (s) url += '?' + s;
    } else {
      body = JSON.stringify(input ?? {});
    }

    const res = await this.fetchImpl(url, { method, headers, body });
    const json: unknown = await res.json().catch(() => undefined);
    if (!res.ok) throw new AtlasApiError(res.status, json);
    return json as T | ApprovalPending;
  }

${methods}
}

export function createGeneratedClient(opts: AtlasClientOptions): AtlasGeneratedClient {
  return new AtlasGeneratedClient(opts);
}
`;
}

// ---------- emit ----------

const routesOut = join(repoRoot, 'apps', 'api', 'src', 'routes.gen.ts');
const clientOut = join(repoRoot, 'packages', 'client', 'src', 'client.gen.ts');

mkdirSync(dirname(routesOut), { recursive: true });
mkdirSync(dirname(clientOut), { recursive: true });
writeFileSync(routesOut, genRoutes(registry));
writeFileSync(clientOut, genClient(registry));

console.log(`codegen: wrote ${routesOut} (${registry.length} routes)`);
console.log(`codegen: wrote ${clientOut} (${registry.length} methods)`);
